import { Card } from '@/components/common/Card';
import Layout from '@/components/layout';
import { SearchBar } from '@/components/mainPage/SearchBar';
import { Select } from '@/components/mainPage/Select';
import { dataType } from '@/types/mainTypes';
import Head from 'next/head';

export default function Home({ data: countries }: dataType) {
  return (
    <>
      <Head>
        <title>Masir REST Countries API</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <div className='flex flex-col justify-between mb-7 relative flex-wrap sm:flex-row'>
            <SearchBar />
            <Select />
          </div>
          <div className=' flex justify-around flex-wrap align-baseline  gap-y-12'>
            {countries.map((item) => {
              return (
                <Card
                  region={item?.region}
                  capital={item?.capital}
                  alt={item?.flags?.alt}
                  country={item?.name.common}
                  key={item?.area}
                  flag={item.flags.svg}
                  population={item.population}
                />
              );
            })}
          </div>
        </Layout>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await res.json();
  return { props: { data } };
}
