import { Card } from '@/components/common/Card';
import Layout from '@/components/layout';
import { SearchBar } from '@/components/mainPage/SearchBar';
import { Select } from '@/components/mainPage/Select';
import { countryDetailsType } from '@/types/countryTypes';
import { dataType } from '@/types/mainTypes';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { api } from './api';

export default function Home({ data: countries }: dataType) {
  const [searchWord, setSearchWord] = useState<string>('');
  const [searchResult, setSearchResult] = useState<countryDetailsType>();
  useEffect(() => {
    if (searchWord?.length != 0) {
      const searchRequest = async () => {
        try {
          const res = await api.getSingleDetail(searchWord);
          const result: countryDetailsType = res?.data[0];
          setSearchResult(result);
        } catch (err) {
          console.log(err);
        }
      };
      searchRequest();
    }
  }, []);
  useEffect(() => {
    const searchWordArray = searchWord.split('');
    const searchResult = countries.filter((item) => {
      const countryNameArray = item.name.common.split('');
      return searchWordArray.every((searchLetter) =>
        countryNameArray.includes(searchLetter)
      );
    });
    console.log(searchResult);
  }, [searchWord]);

  console.log(searchResult);
  return (
    <>
      <Head>
        <title>Masir REST Countries API</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <div className='flex flex-col justify-between mb-7 relative flex-wrap sm:flex-row'>
            <SearchBar setSearchWord={setSearchWord} />
            <Select />
          </div>
          <div className=' flex justify-around flex-wrap align-baseline  gap-y-12'>
            {countries.map((item) => {
              return (
                <Card
                  region={item?.region}
                  capital={item?.capital}
                  alt={item?.flags?.alt}
                  country={item?.name.common}
                  key={item?.area}
                  flag={item.flags.svg}
                  population={item.population}
                />
              );
            })}
          </div>
        </Layout>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch(`https://restcountries.com/v3.1/all`);
  const data = await res.json();
  return { props: { data } };
}
