import { Card } from '@/components/common/Card';
import Layout from '@/components/layout';
import { SearchBar } from '@/components/mainPage/SearchBar';
import { Select } from '@/components/mainPage/Select';
import { Inter } from '@next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Masir REST Countries API</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <div className='flex justify-between mb-7 relative '>
            <SearchBar />
            <Select />
          </div>
          <div className=' flex justify-around flex-wrap align-baseline  gap-y-12'>
            {[...Array(20)].map((item, index) => (
              <Card key={index} />
            ))}
          </div>
        </Layout>
      </main>
    </>
  );
}
